application: trains-gae
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /scripts
  static_dir: scripts
- url: /.*
  script: trains.py

libraries:
- name: jinja2
  version: latest
